type TickerToNameMap = { [ticker: string]: string };

export const tickerToName: TickerToNameMap = {
  NAB: 'Sodium Borohydride',
  LCR: 'Liquid Crystals',
  JUI: 'Sedative Substance',
  IND: 'Indigo Colorant',
  FLX: 'Flux',
  ETC: 'Enriched Technetium',
  EES: 'Enriched Einsteinium',
  OLF: 'Olfactory Substances',
  PFE: 'Premium Fertilizer',
  REA: 'Chemical Reagents',
  SOI: 'Artificial Soil',
  TCL: 'TCL Acid',
  THF: 'ThermoFluid',
  CMK: 'Core Module Kit',
  NG: 'Nano-Coated Glass',
  NFI: 'Nano Fiber',
  NCS: 'Nano-Carbon Sheeting',
  MTC: 'MegaTube Coating',
  MCG: 'Mineral Construction Granulate',
  INS: 'InsuFoam',
  GL: 'Glass',
  EPO: 'Epoxy Resin',
  RG: 'Reinforced Glass',
  SEA: 'Poly-Sulfite Sealant',
  AEF: 'Aerostat Foundation',
  AIR: 'Air Scrubber',
  DEC: 'Decorative Elements',
  FC: 'Flow Control Device',
  FLO: 'Floating Tank',
  FLP: 'Fluid Piping',
  TCS: 'Stabilized Technetium',
  RSH: 'Radiation Shielding',
  PSH: 'Pressure Shielding',
  MHL: 'Metal-Halide Lighting System',
  MGC: 'Magnetic Ground Cover',
  LIT: 'Neon Lighting System',
  GV: 'Gas Vent',
  GC: 'Cylindrical Gas Container',
  TRU: 'Truss',
  TSH: 'Thermal Shielding',
  BBH: 'Basic Bulkhead',
  BDE: 'Basic Deck Elements',
  BSE: 'Basic Structural Elements',
  BTA: 'Basic Transparent Aperture',
  LBH: 'Lightweight Bulkhead',
  LDE: 'Lightweight Deck Elements',
  ADE: 'Advanced Deck Elements',
  ABH: 'Advanced Bulkhead',
  RTA: 'Reinforced Transparent Aperture',
  RSE: 'Reinforced Structural Elements',
  RDE: 'Reinforced Deck Elements',
  RBH: 'Reinforced Bulkhead',
  LTA: 'Lightweight Transparent Aperture',
  LSE: 'Lightweight Structural Elements',
  ASE: 'Advanced Structural Elements',
  ATA: 'Advanced Transparent Aperture',
  HSE: 'Hardened Structural Elements',
  DW: 'Drinking Water',
  RAT: 'Basic Rations',
  OVE: 'Basic Overalls',
  EXO: 'Exoskeleton Work Suit',
  PT: 'Power Tools',
  LC: 'AI-Assisted Lab Coat',
  MEA: 'Quality Meat Meal',
  PDA: 'Personal Data Assistant',
  HSS: 'Smart Space Suit',
  FIM: 'Flavoured Insta-Meal',
  SCN: 'Multi-Purpose Scanner',
  HMS: 'HazMat Work Suit',
  MED: 'Basic Medical Kit',
  MPC: 'Micro-Processor',
  PCB: 'Printed Circuit Board',
  RAM: 'Memory Bank',
  ROM: 'Non-Volatile Memory',
  SEN: 'Sensor',
  TPU: 'Tensor Processing Unit',
  MWF: 'Medium Wafer',
  MFK: 'Medium Fastener Kit',
  LDI: 'Laser Diodes',
  HCC: 'High-Capacity Connectors',
  CAP: 'Electric Field Capacitor',
  BGC: 'Shielded Connectors',
  BCO: 'Budget Connectors',
  TRA: 'Audio Transmitter',
  SFK: 'Small Fastener Kit',
  SWF: 'Small Wafer',
  TRN: 'Advanced Transistor',
  ACS: 'Automated Cooling System',
  ADS: 'Audio Distribution System',
  CC: 'Climate Controller',
  COM: 'Communication System',
  CRU: 'Cryogenic Unit',
  C: 'Carbon',
  BE: 'Beryllium',
  WR: 'Water Reclaimer',
  TAC: 'Targeting Computer',
  STS: 'Stability Support System',
  LOG: 'Logistics System',
  LIS: 'Life Support System',
  FFC: 'FTL Field Controller',
  CA: 'Calcium',
  CL: 'Chlorine',
  ES: 'Einsteinium',
  I: 'Iodine',
  MG: 'Magnesium',
  NA: 'Sodium',
  S: 'Sulfur',
  TA: 'Tantalum',
  SP: 'Solar Panel',
  SOL: 'Solar Cell',
  POW: 'Power Cell',
  CBS: 'Small Capacitor Bank',
  CBM: 'Medium Capacitor Bank',
  CBL: 'Large Capacitor Bank',
  ZR: 'Zirconium',
  TC: 'Technetium',
  FF: 'FTL Fuel',
  SF: 'STL Fuel',
  AMM: 'Ammonia',
  AR: 'Argon',
  F: 'Fluorine',
  H: 'Hydrogen',
  HE: 'Helium',
  HE3: 'Helium-3 Isotope',
  ADR: 'Auto-Doc',
  LES: 'Liquid Einsteinium',
  HEX: 'Heliotrope Extract',
  H2O: 'Water',
  BTS: 'Bacterial Tungsten Solution',
  O: 'Oxygen',
  NE: 'Neon',
  N: 'Nitrogen',
  BND: 'Bandages',
  PK: 'Painkillers',
  SEQ: 'Surgical Equipment',
  STR: 'Medical Stretcher',
  TUB: 'Test Tubes',
  AL: 'Aluminium',
  AU: 'Gold',
  CU: 'Copper',
  BOR: 'Boron Crystals',
  BER: 'Beryl Crystals',
  W: 'Tungsten',
  TI: 'Titanium',
  STL: 'Steel',
  SI: 'Silicon',
  LI: 'Lithium',
  FE: 'Iron',
  BRM: 'Bioreactive Minerals',
  CLI: 'Caliche Rock',
  GAL: 'Galerite Rock',
  HAL: 'Halite Crystals',
  LST: 'Limestone',
  MAG: 'Magnetite',
  MGS: 'Magnesite',
  SCR: 'Sulfur Crystals',
  FEO: 'Iron Ore',
  CUO: 'Copper Ore',
  AUO: 'Gold Ore',
  ALO: 'Aluminium Ore',
  ZIR: 'Zircon Crystals',
  TS: 'Tectosilisite',
  TCO: 'Technetium Oxide',
  TAI: 'Tantalite Rock',
  LIO: 'Lithium Ore',
  SIO: 'Silicon Ore',
  TIO: 'Titanium Ore',
  DCL: 'Durable Casing L',
  DCM: 'Durable Casing M',
  DCS: 'Durable Casing S',
  PE: 'Poly-Ethylene',
  PG: 'Polymer Granulate',
  BFP: 'Basic Fuel Pump',
  ANZ: 'Advanced Nozzle',
  AFR: 'Advanced Fuel Rod',
  AFP: 'Advanced Fuel Pump',
  AEN: 'Advanced STL Engine',
  PSS: 'Polymer Sheet Type S',
  PSM: 'Polymer Sheet Type M',
  PSL: 'Polymer Sheet Type L',
  BFR: 'Basic Fuel Rod',
  CHA: 'Combustion Chamber',
  ENG: 'Standard STL Engine',
  FIR: 'Fission Reactor',
  FSE: 'Fuel-saving STL Engine',
  GCH: 'Glass Combustion Chamber',
  GEN: 'Glass-based STL Engine',
  GNZ: 'Glass Nozzle',
  MCB: 'Medium Cargo Bay Kit',
  MFE: 'Medium FTL Emitter',
  MFL: 'Medium FTL Fuel Tank Kit',
  MHP: 'Micro Headphones',
  MLI: 'Machine Learning Interface',
  MSL: 'Medium STL Fuel Tank Kit',
  MTP: 'Meat Tissue Patties',
  MUS: 'Protein-Rich Mushrooms',
  NF: 'Networking Framework',
  NL: 'Nylon Fabric',
  NN: 'Neural Network',
  NOZ: 'Basic Nozzle',
  NR: 'Nano-Enhanced Resin',
  NS: 'Nutrient Solution',
  NST: 'NeuroStimulants',
  NUT: 'Triglyceride Nuts',
  NV1: 'Navigation Module MK1',
  NV2: 'Navigation Module MK2',
  OFF: 'Office Supplies',
  OS: 'Operating System',
  PIB: 'Pineberries',
  PPA: 'Protein Paste',
  PWO: 'Padded Work Overall',
  QCR: 'Quick-charge FTL Reactor',
  RAD: 'Radio Device',
  RAG: 'Radioisotope Generator',
  RCO: 'Raw Cotton Fiber',
  RCS: 'Reactor Control System',
  RCT: 'Standard FTL Reactor',
  RDL: 'Large Ship-Repair Drone Operations Unit',
  RDS: 'Small Ship-Repair Drone Operations Unit',
  RED: 'Rescue Drone',
  REP: 'Repair Kit',
  RGO: 'Red Gold',
  RHP: 'Reinforced Hull Plate',
  RSI: 'Raw Silk Strains',
  SA: 'Search Algorithm',
  SAL: 'Sorting Algorithm',
  SAR: 'Sensor Array',
  SC: 'Stem Cell Treatment',
  SCB: 'Small Cargo Bay Kit',
  SDR: 'Surgical Drone',
  SFE: 'Small FTL Emitter',
  SFL: 'Small FTL Fuel Tank Kit',
  SIL: 'Silken Fabric',
  SNM: 'Spatial Navigation Map',
  SRD: 'Ship-Repair Drone',
  SRP: 'Specialized Anti-rad Plate',
  SSC: 'Structural Spacecraft Component',
  SSL: 'Small STL Fuel Tank Kit',
  SU: 'Surgery Unit',
  SUD: 'Surveillance Drone',
  SUN: 'Safety Uniform',
  TCB: 'Tiny Cargo Bay Kit',
  TCU: 'Trauma Care Unit',
  THP: 'Basic Thermal Protection Material',
  TK: 'Enhanced Para Aramid',
  UTS: 'Universal Toolset',
  VCB: 'High-volume Cargo Bay Kit',
  VEG: 'Triglyceride Fruits',
  VG: 'VitaGel',
  VIT: 'Vita Essence',
  VSC: 'Very Small Cargo Bay Kit',
  WAI: 'Weak Artificial Intelligence',
  WAL: 'Alpha-Stabilized Tungsten',
  WCB: 'High-load Cargo Bay Kit',
  WIN: 'Smart Zinfandel',
  WM: 'Window Manager',
  WOR: 'Handcraft Workshop Unit',
  WS: 'Scientific Work Station',
  BLE: 'Desaturation Agent',
  BMF: 'Basic Mainframe',
  BOS: 'Borosilicate',
  BPT: 'Basic Thermal Protection Tile',
  BR1: 'Command Bridge MK1',
  BR2: 'Command Bridge MK2',
  BRO: 'Bronze',
  BRP: 'Basic Anti-rad Plate',
  BRS: 'Short-distance Command Bridge',
  BSC: 'Body Scanner',
  BWH: 'Basic Whipple Shielding',
  BWS: 'Basic Workstation',
  CAF: 'Caffeinated Beans',
  CCD: 'Crowd Control Drone',
  CD: 'Capacitive Display',
  CF: 'Ceramic Fabric',
  COF: 'Caffeinated Infusion',
  COT: 'Cotton Fabric',
  CQL: 'Crew Quarters (Large)',
  CQM: 'Crew Quarters (Medium)',
  CQS: 'Crew Quarters (Small)',
  CQT: 'Crew Quarters (Tiny)',
  CST: 'Cryogenic Stabilizer',
  CTF: 'Ceramic-Tungsten Fabric',
  DA: 'Data Analyzer',
  DCH: 'Drone Chassis',
  DD: 'Distributed Database',
  DDT: 'DDT Plant Agent',
  DIS: 'Information Display',
  DOU: 'Drone Operations Unit',
  DRF: 'Drone Frame',
  DV: 'Data Visualizer',
  EDC: 'Entertainment Data Core',
  FAL: 'Ferrominium',
  FAN: 'Active Cooling Device',
  FET: 'Ferro-Titanium',
  FOD: 'All-Purpose Fodder',
  FUN: 'Entertainment Unit',
  GIN: 'Einsteinium-Infused Gin',
  GRA: 'Wine-Quality Grapes',
  GRN: 'High-Carb Grains',
  HAB: 'Habitat Unit',
  HCB: 'Huge Cargo Bay Kit',
  HCP: 'Hydrocarbon Plants',
  HD: 'Holographic Display',
  HER: 'Spicy Herbs',
  HHP: 'Hardened Hull Plate',
  HNZ: 'Hyperthrust Nozzle',
  HOG: 'Holographic Glasses',
  HOP: 'Flowery Hops',
  HPC: 'Handheld Personal Console',
  HPR: 'High-power FTL Reactor',
  HTE: 'Hyperthrust STL Engine',
  HYR: 'Hyper-power Reactor',
  IDC: 'Information Data Core',
  IMM: 'Information Management System',
  KOM: 'Kombucha',
  KV: 'Para Aramid',
  LCB: 'Large Cargo Bay Kit',
  LD: 'Local Database',
  LFE: 'Large FTL Emitter',
  LFL: 'Large FTL Fuel Tank Kit',
  LFP: 'Low-heat Fuel Pump',
  LHP: 'Lightweight Hull Plate',
  LSL: 'Large STL Fuel Tank Kit',
  LU: 'Laboratory Unit',
  MAI: 'High-Carb Maize',
  MB: 'Motherboard',
  AAR: 'Antenna Array',
  AGS: 'Advanced High-G Seats',
  AHP: 'Advanced Hull Plate',
  ALE: 'Stellar Pale Ale',
  ALG: 'Protein-Rich Algae',
  APT: 'Advanced Thermal Protection Tile',
  ARP: 'Advanced Anti-rad Plate',
  AST: 'Alpha-Stabilized Titanium',
  ATP: 'Advanced Thermal Protection Material',
  AWF: 'Active Water Filter',
  AWH: 'Advanced Whipple Shielding',
  BAC: 'Helpful Bacteria',
  BAI: 'Basic AI Framework',
  BEA: 'Protein-Rich Beans',
  BGO: 'Blue Gold',
  BGS: 'Basic High-G Seats',
  BHP: 'Basic Hull Plate',
  BID: 'Full-Body Interaction Device',
  BL: 'Breathable Liquid',
};

export function searchForTickerFromName(substring: string): string[] {
  return (
    Object.keys(tickerToName).filter(key =>
      tickerToName[key].toLowerCase().includes(substring.toLowerCase()),
    ) ?? []
  );
}
