import classes from './icons-pictograms.module.css';
import PrunCss from '@src/infrastructure/prun-ui/prun-css';
import features from '@src/feature-registry';
import {
  applyCssRule,
  applyRawCssRule,
  endCssAtScope,
  startCssAtScope,
} from '@src/infrastructure/prun-ui/refined-prun-css';
import { companyStore } from '@src/infrastructure/prun-api/data/company';
import { objectKeys } from 'ts-extras';

function init() {
  if (companyStore.value?.code !== 'SN') {
    return;
  }

  applyCssRule(`.${PrunCss.ColoredIcon.container}`, classes.container);
  applyCssRule(`.${PrunCss.ColoredIcon.container}:before`, classes.containerBefore);
  applyCssRule(`.${PrunCss.ColoredIcon.label}:before`, classes.labelBefore);

  startCssAtScope('@container (height < 24px)');
  applyCssRule(`.${PrunCss.ColoredIcon.container}:before`, classes.hide);
  applyCssRule(`.${PrunCss.ColoredIcon.label}:before`, classes.hide);
  endCssAtScope();

  for (const category of objectKeys(categories)) {
    const selector = `.${PrunCss.ColoredIcon.container}[data-rp-category='${category}']:before `;
    const rule = createRule(categories[category]);
    applyRawCssRule(selector + rule);
  }
  for (const material of objectKeys(materials)) {
    const selector = `.${PrunCss.ColoredIcon.container}[data-rp-ticker='${material}']:before `;
    const rule = createRule(materials[material]);
    applyRawCssRule(selector + rule);
  }
}

function createRule(pictogram: Pictogram) {
  const hasOptions = typeof pictogram !== 'string';
  const character = hasOptions ? pictogram[0] : pictogram;
  let fontSize = pictogramFontSize[character];
  let rule = '{';
  if (hasOptions) {
    const options = pictogram[1];
    if (options.opacity) {
      rule += ` opacity: ${options.opacity};`;
    }
    if (options.fontSize) {
      fontSize = options.fontSize;
    }
  }
  rule += ` content: '${character}';`;
  if (fontSize) {
    rule += ` font-size: calc(${fontSize} * 2em);`;
  }
  rule += ' }';
  return rule;
}

type Pictogram = string | [string, { opacity?: number; fontSize?: number }];

const pictogramFontSize: Record<string, number> = {
  '☀': 1.2,
  '♨': 1.2,
  '☣': 1.8,
  '⛓': 1.6,
  '✈': 1.8,
  '❄': 1.2,
  '🎞': 1.1,
  '🔧': 1.1,
  '🔶': 1.1,
  '🔷': 1.1,
  '🔺': 1.5,
  '🛏': 1.1,
  '🛡': 1.2,
  '🛢': 1.2,
  '🛸': 1.2,
  '🧰': 1.1,
  '🧳': 1.2,
  '🪑': 1.1,
  '👓': 1.4,
  '🚿': 1.4,
  '🔲': 1.1,
  '🎟': 1.1,
  '🧵': 1.2,
  '🧊': 1.2,
  '🔭': 1.1,
};

const categories: Record<string, Pictogram> = {
  'agricultural products': '',
  alloys: ['', { opacity: 0.4 }],
  chemicals: '🧪',
  'construction materials': '',
  'construction parts': '',
  'construction prefabs': '',
  'consumables (basic)': ['', { opacity: 0.2 }],
  'consumables (luxury)': ['', { opacity: 0.2 }],
  drones: '✈',
  'electronic devices': '',
  'electronic parts': '',
  'electronic pieces': '',
  'electronic systems': ['🖥', { opacity: 0.6 }],
  elements: '⛰',
  'energy systems': '',
  fuels: '',
  gases: '☁',
  liquids: '',
  'medical equipment': '',
  metals: ['⛰', { opacity: 0.3 }],
  minerals: ['⛰', { opacity: 0.4 }],
  ores: '🥔',
  plastics: '',
  'ship engines': ['', { opacity: 0.4 }],
  'ship kits': ['', { opacity: 0.4 }],
  'ship parts': '',
  'ship shields': '🛡',
  'software components': '💾',
  'software systems': '💾',
  'software tools': '💾',
  textiles: '',
  'unit prefabs': ['', { opacity: 0.4 }],
  utility: '',
};

const materials: Record<string, Pictogram> = {
  AAR: '📡',
  ABH: '🛸',
  ADE: '🎞',
  ADR: '👨‍⚕️',
  ADS: '🔊',
  AEF: '🧇',
  AEN: '🚀',
  AFP: '🚰',
  AFR: '🧨',
  AGS: ['🪑', { opacity: 0.6 }],
  AHP: '🛡',
  AIR: '☁',
  AL: '⬜',
  ALE: '🍺',
  ALG: '🍃',
  AMM: '🩸',
  ANZ: '⛰',
  ASE: '⛓',
  AST: '🟪',
  ATA: '🏗',
  ATP: '🧱',
  AU: '🟨',
  AWF: '📻',
  BAC: '🧫',
  BBH: '🛸',
  BCO: ['🔌', { opacity: 0.4 }],
  BDE: '🎞',
  BE: '⛰',
  BEA: '🥒',
  BER: '💎',
  BFP: '🚰',
  BFR: ['🧨', { fontSize: 0.8 }],
  BGC: ['🔌', { opacity: 0.4 }],
  BGO: '🔷',
  BGS: ['🪑', { opacity: 0.6 }],
  BHP: '🛡',
  BID: '📻',
  BL: '💧',
  BMF: '🖥',
  BND: '🧻',
  BOR: '💎',
  BOS: '〰',
  BR1: '☎',
  BR2: '☎',
  BRO: '🔺',
  BRS: '☎',
  BSC: '🔭',
  BSE: '⛓',
  BTA: '🏗',
  BTS: '🧪',
  BWS: '💻',
  C: '🎩',
  CA: '⛰',
  CAF: '🌿',
  CAP: '🔋',
  CBL: ['🔋', { fontSize: 1.1 }],
  CBM: '🔋',
  CBS: ['🔋', { fontSize: 0.8 }],
  CC: ['🎛', { opacity: 0.6 }],
  CD: '💻',
  CF: '🧵',
  CHA: '🧳',
  CL: '🍥',
  CLI: '🥯',
  COF: '☕',
  COT: '🧵',
  CQL: ['🛏', { fontSize: 1.2 }],
  CQM: '🛏',
  CQS: ['🛏', { fontSize: 1 }],
  CQT: ['🛏', { fontSize: 0.75 }],
  CRU: '❄',
  CST: '❄',
  CTF: '🧵',
  CU: '🟧',
  DCL: ['🧊', { fontSize: 1.4 }],
  DCM: '🧊',
  DCS: ['🧊', { fontSize: 1 }],
  DEC: '🖼',
  DIS: '💻',
  DOU: '✈',
  DW: '🧃',
  ENG: '🚀',
  EPO: '🧪',
  EXO: '👷‍♀️',
  FAL: '🟦',
  FAN: '📻',
  FC: '🚿',
  FE: '🟦',
  FET: '🟪',
  FF: ['☀', { opacity: 0.5 }],
  FFC: '☀',
  FIM: '🥡',
  FIR: ['🎆', { fontSize: 0.8 }],
  FLO: '🛢',
  FLP: ['🚰', { opacity: 0.4 }],
  FOD: '💊',
  FSE: '🚀',
  FUN: '🎡',
  GAL: '🥯',
  GC: '☁',
  GEN: '🚀',
  GIN: '🥃',
  GL: '🔲',
  GNZ: '⛰',
  GRA: '🍇',
  GRN: '🌾',
  GV: ['♨', { opacity: 0.4 }],
  H: '💫',
  H2O: '💧',
  HAB: '🏠',
  HAL: '💎',
  HCC: ['🔌', { opacity: 0.4 }],
  HCP: '🌲',
  HD: '💻',
  HE: '🌌',
  HE3: '💦',
  HER: '🌶',
  HEX: '🥃',
  HHP: '🛡',
  HMS: '👩‍🚒',
  HNZ: '⛰',
  HOG: '👓',
  HOP: '🌾',
  HPC: '📱',
  HPR: '🎆',
  HSE: '⛓',
  HSS: '👨‍🚀',
  HTE: '🚀',
  HYR: '🎆',
  I: '🩸',
  INS: '🌫',
  KOM: '🍯',
  LBH: '🛸',
  LC: '🥼',
  LCB: ['📦', { fontSize: 1.1 }],
  LCR: '💎',
  LDE: '🎞',
  LDI: '▶',
  LES: '🥛',
  LFE: '📡',
  LFL: '🧳',
  LFP: '🚰',
  LHP: '🛡',
  LIT: '💡',
  LSE: '⛓',
  LSL: '🛢',
  LST: '🥯',
  LTA: '🏗',
  MAG: '🧲',
  MAI: '🌽',
  MB: '🎫',
  MCB: '📦',
  MCG: '🧱',
  MEA: '🍱',
  MED: '🩺',
  MFE: ['📡', { fontSize: 0.8 }],
  MFK: '🔧',
  MFL: ['🧳', { fontSize: 1 }],
  MG: '⛰',
  MGC: '🧲',
  MHL: '💡',
  MHP: '🎧',
  MPC: '🎟',
  MSL: ['🛢', { fontSize: 1 }],
  MTC: '🧪',
  MTP: '🧫',
  MUS: '🍄',
  MWF: '🎫',
  N: '💧',
  NA: '🧂',
  NAB: '🧂',
  NCS: '🎩',
  NFI: '🧵',
  NG: '🔲',
  NL: '🧵',
  NOZ: '⛰',
  NS: '🧪',
  NST: '💊',
  NUT: '🥜',
  NV1: '💾',
  NV2: '💾',
  O: '💨',
  OFF: '📠',
  OVE: '🧥',
  PCB: '🎫',
  PDA: '📱',
  PE: '⚾',
  PG: '🏐',
  PIB: '🍓',
  PK: '💊',
  POW: ['🔋', { fontSize: 0.7 }],
  PPA: '🥣',
  PSH: '🛡',
  PSL: ['🧻', { fontSize: 1.2 }],
  PSM: '🧻',
  PSS: ['🧻', { fontSize: 0.8 }],
  PT: '🔌',
  PWO: '🦺',
  QCR: '🎆',
  RAD: '📻',
  RAG: ['🎆', { fontSize: 0.8 }],
  RAM: '🎞',
  RAT: '🥫',
  RBH: '🛸',
  RCO: '🧶',
  RCS: '🖥',
  RCT: '🎆',
  RDE: '🎞',
  RDL: '✈',
  RDS: '✈',
  REP: '🧰',
  RG: '🔲',
  RGO: '🔶',
  RHP: '🛡',
  ROM: '📀',
  RSE: '⛓',
  RSH: '🛡',
  RSI: '🧶',
  RTA: '🏗',
  S: '🟡',
  SAR: '🔭',
  SC: '💉',
  SCB: ['📦', { fontSize: 0.9 }],
  SCN: '🔭',
  SCR: '💎',
  SEA: '🌫',
  SEN: '🔭',
  SEQ: '🩺',
  SF: ['🛢', { opacity: 0.5 }],
  SFE: ['📡', { fontSize: 0.7 }],
  SFK: ['🔧', { fontSize: 0.9 }],
  SFL: ['🧳', { fontSize: 0.8 }],
  SI: '〰',
  SIL: '🧵',
  SOI: '🥔',
  SOL: ['⚡', { fontSize: 0.8 }],
  SP: '⚡',
  SSC: ['⛓', { opacity: 0.4 }],
  SSL: ['🛢', { fontSize: 0.8 }],
  STL: '🧊',
  STR: '🎞',
  SU: '⚕',
  SUN: '👖',
  SWF: ['🎫', { fontSize: 0.9 }],
  TA: '🔘',
  TAI: '🥯',
  TCB: ['📦', { fontSize: 0.75 }],
  TCL: '☣',
  TCS: '⛰',
  TCU: '🛏',
  THP: '🧱',
  TI: '🟪',
  TPU: '🧮',
  TRA: '🔊',
  TRN: '🎟',
  TRU: '🗼',
  TSH: '🛡',
  TUB: '🧪',
  UTS: ['🛠', { opacity: 0.4 }],
  VCB: ['📦', { fontSize: 1.1 }],
  VEG: '🍅',
  VG: '🧪',
  VIT: '🍶',
  VSC: ['📦', { fontSize: 0.8 }],
  W: '🟫',
  WAL: '🟫',
  WCB: ['📦', { fontSize: 1.1 }],
  WIN: '🍷',
  WOR: '🎨',
  WR: '💧',
  WS: '🔬',
  ZIR: '💎',
};

void features.add({
  id: 'icons-pictograms',
  init,
});
