/**
 * A list of the material names and their corresponding ticker, weight, and volume. Makes it easier to reference FIO data
 *
 */

export const CurrencySymbols = {
  CIS: '₡',
  AIC: '₳',
  NCC: '₦',
  ICA: 'ǂ',
  ECD: '€',
};
export const FactionHeaders = {
  'Castillo-Ito': 'CI',
  Insitor: 'IC',
  Antares: 'AI',
  'NEO Charter': 'NC',
};
export const RatingColors = {
  P: '#1b6b9c',
  U: '#8b211e',
  F: '#e26c37',
  E: '#e7782b',
  D: '#e87d28',
  C: '#ed891c',
  B: '#f19510',
  A: '#f6a204',
};

export const Consumption = {
  PIO: {
    RAT: 4,
    DW: 4,
    OVE: 0.5,
    PWO: 0.2,
    COF: 0.5,
  },
  SET: {
    DW: 5,
    RAT: 6,
    EXO: 0.5,
    PT: 0.5,
    KOM: 1,
    REP: 0.2,
  },
  TEC: {
    DW: 7.5,
    RAT: 7,
    MED: 0.5,
    HMS: 0.5,
    SCN: 0.1,
    ALE: 1,
    SC: 0.1,
  },
  ENG: {
    DW: 10,
    MED: 0.5,
    FIM: 7,
    HSS: 0.2,
    PDA: 0.1,
    VG: 0.2,
    GIN: 1,
  },
  SCI: {
    DW: 10,
    MED: 0.5,
    MEA: 7,
    LC: 0.2,
    WS: 0.1,
    WIN: 1,
    NST: 0.1,
  },
};

export const Exchanges = {
  'Antares Station Commodity Exchange': 'ANT',
  'Benten Station Commodity Exchange': 'BEN',
  'Moria Station Commodity Exchange': 'MOR',
  'Hortus Station Commodity Exchange': 'HRT',
  'Hubur Commodity Exchange': 'HUB',
  'Arclight Commodity Exchange': 'ARC',
};
export const ExchangeTickers = { ANT: 'AI1', BEN: 'CI1', MOR: 'NC1', HRT: 'IC1', HUB: 'NC2', ARC: 'CI2' };
export const ExchangeTickersReverse = {
  AI1: 'ANT',
  CI1: 'BEN',
  NC1: 'MOR',
  IC1: 'HRT',
  NC2: 'HUB',
  CI2: 'ARC',
};
export const Stations = {
  'Antares Station': 'ANT',
  'Benten Station': 'BEN',
  'Moria Station': 'MOR',
  'Hortus Station': 'HRT',
  'Hubur Station': 'HUB',
  'Arclight Station': 'ARC',
};

export const NonProductionBuildings = ['CM', 'HB1', 'HB2', 'HB3', 'HB4', 'HB5', 'HBB', 'HBC', 'HBL', 'HBM', 'STO'];

export const FriendlyNames = {
  LocalMarketAds: 'LM Unit Prices',
  OrderETAs: 'Order ETAs',
  FlightETAs: 'Flight Planning ETAs',
  ShippingAds: 'LM Shipping Rates',
  PostLM: 'LM Posting Unit Price',
  ContractDrafts: 'CONTD Unit Prices',
  QueueLoad: 'Queue Percent Display',
  ConsumableTimers: 'Workforce Consumable Burn',
  FleetETAs: 'Fleet ETAs',
  Notifications: 'Notifications',
  ScreenUnpack: 'Screen Unpack',
  ImageCreator: 'Chat Image Creator',
  InventoryOrganizer: 'Inventory Sorting',
  CommandCorrecter: 'Command Correcter',
  CalculatorButton: 'Calculator Button',
  Sidebar: 'Sidebar',
  HeaderMinimizer: 'Minimize Headers (Master)',
  PendingContracts: 'Pending Contracts',
  CompactUI: 'Compact UI',
  FormulaReplacer: 'Formula Replacer',
  AdvancedMode: 'Advanced Minimialist Mode (Master)',
  CXOBHighlighter: 'CXOB Name Highlighter',
  CXPOOrderBook: 'CXPO Order Book',
  ChatDeleteButton: 'Toggle Chat Delete (Master)',
};

export const SortingTriangleHTML = `
<div title=""><svg aria-hidden="true" width="10" height="10" role="img" version="1.1" fill="currentcolor" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24" style="vertical-align: middle;"><g><path d="M.88681 1.097752l12.13774 21.02318L25.422964 1.105446z"></path></g></svg></div>`;

export const PlanetCommands = [
  'ADM',
  'BSC',
  'COGC',
  'COGCPEX',
  'COGCU',
  'FLTP',
  'LR',
  'LMP',
  'LM',
  'PLI',
  'POPI',
  'POPR',
  'PPS',
  'SHY',
  'WAR',
  'BS',
  'BRA',
  'GOV',
];

export const SystemNames = {
  ARCLIGHT: 'AM-783',
  'FORGE-KEEP': 'FK-371',
  'WET WATER': 'FK-794',
  'CAYMAN PLANETS': 'GC-645',
  'MOUNT OLYMPUS': 'HM-049',
  GATEWAY: 'HM-223',
  'NEO EDEN': 'JS-299',
  EBISU: 'JS-952',
  BASTABLON: 'KW-020',
  DOLZENA: 'LG-418',
  'ANTARES V': 'LS-300',
  TRINITY: 'OF-259',
  GUNDABAD: 'OT-442',
  MORIA: 'OT-580',
  'OUTER HEAVEN': 'PG-899',
  AURUM: 'QJ-650',
  ACETARES: 'QJ-684',
  HUBUR: 'TD-203',
  HOTEI: 'UV-135',
  BENTEN: 'UV-351',
  DAIKOKU: 'UV-796',
  RATHAR: 'VH-043',
  HORTUS: 'VH-331',
  MIDWAY: 'WB-675',
  BASTION: 'XG-326',
  'ANTARES III': 'ZV-194',
  'ANTARES I': 'ZV-307',
  'ANTARES II': 'ZV-759',
  'ANTARES IV': 'ZV-896',
};

export const PlanetNames = {
  LEMURIA: 'AJ-768a',
  GALLUS: 'AM-783b',
  EMENTIOR: 'AM-783c',
  TYPHON: 'AU-522b',
  'NOVA HONSHU': 'BS-788c',
  TACOTOPIA: 'CB-045b',
  JOTU: 'CG-044c',
  PYRGOS: 'CH-771a',
  TALOSIA: 'DC-823b',
  ORM: 'DW-456g',
  MANIFOLD: 'EL-179b',
  'NOVA UNALASKA': 'EZ-476b',
  TOKTU: 'FK-037f',
  'LA FORGE': 'FK-371b',
  BOUCHER: 'FK-794b',
  EPICIER: 'FK-794c',
  VAULT: 'GC-645b',
  CHU: 'GY-110c',
  POSEIDON: 'HM-049b',
  APOTHECARY: 'IA-603b',
  ELECTRONICA: 'IY-028c',
  NEMESIS: 'JS-299a',
  GIBSON: 'JS-952c',
  AUSTRALIA: 'KI-446a',
  DEMETER: 'KI-446b',
  HERMES: 'KI-448b',
  ROCK: 'KQ-966b',
  MILLIWAYS: 'KW-020c',
  'GIEDI PRIME': 'KW-358b',
  ETHERWIND: 'KW-688c',
  KINZA: 'LG-418b',
  'PLANET MC PLANETFACE': 'LG-913e',
  ARATORA: 'LS-231b',
  GRIFFONSTONE: 'LS-300c',
  JURA: 'OF-259d',
  BERTHIER: 'OF-375b',
  ADALINA: 'OF-375c',
  AKKALA: 'OF-586b',
  DANAKIL: 'OT-442b',
  MANAKIL: 'OT-442h',
  IIRON: 'OT-580a',
  MONTEM: 'OT-580b',
  VALLIS: 'OT-580c',
  PALLADA: 'OT-580d',
  PRISM: 'OT-889a',
  JEETIYU: 'OT-889b',
  ASHLAND: 'PD-754d',
  SALADIN: 'PG-899b',
  NASCENT: 'QJ-149c',
  ELON: 'QJ-650c',
  'LOM PALANKA': 'QJ-684a',
  ACELAND: 'QJ-684b',
  CIRCA: 'QQ-001a',
  CIRCE: 'QQ-001b',
  CELEBDIL: 'QQ-645b',
  MALAHAT: 'RC-040b',
  IRONFORGE: 'RC-040c',
  'ICE STATION ALPHA': 'SE-110c',
  SHEOL: 'TD-203b',
  RHAZES: 'TD-228b',
  SABATON: 'TO-392d',
  ALYAZKCALB: 'UB-402e',
  'ASBESTOS LEAD ASBESTOS': 'UV-072c',
  KATOA: 'UV-351a',
  YANNICK: 'UV-351b',
  UMBRA: 'UV-351c',
  BIOGENESIS: 'UV-351d',
  PROXION: 'UV-796b',
  PHANTASM: 'VH-043a',
  NOBELION: 'VH-043c',
  PROMITOR: 'VH-331a',
  'HELION PRIME': 'VH-331d',
  SHIPTRONIA: 'VH-331e',
  ODYSSEUS: 'VH-331f',
  AVALON: 'VH-331g',
  HYDRON: 'VH-331i',
  SHESMU: 'VH-778b',
  SAND: 'WB-675c',
  GASWORLD: 'WB-675i',
  MIMAR: 'WC-702b',
  MAGUS: 'XD-354b',
  TITAN: 'XG-326b',
  FROST: 'XG-326d',
  UPONOR: 'XH-329a',
  LIBERTAS: 'XH-594a',
  KIRUNA: 'XH-594b',
  CORTEZ: 'XH-594c',
  KUB: 'YI-059f',
  HARPINA: 'YI-209h',
  ARCADIA: 'YI-683c',
  VERDANT: 'YI-715b',
  NORWICK: 'YK-649b',
  NIKE: 'ZV-194a',
  HEPHAESTUS: 'ZV-307c',
  PHOBOS: 'ZV-307d',
  ASTRAEUS: 'ZV-307e',
  VULCAN: 'ZV-759b',
  DEIMOS: 'ZV-759c',
  HARMONIA: 'ZV-896b',
  LIFE: 'ZV-896c',
};

export const MaterialNames = {
  AAR: ['Antenna Array', 'electronic devices'],
  ABH: ['Advanced Bulkhead', 'construction prefabs'],
  ACS: ['Automated Cooling System', 'electronic systems'],
  ADE: ['Advanced Deck Elements', 'construction prefabs'],
  ADR: ['Auto-Doc', 'medical equipment'],
  ADS: ['Audio Distribution System', 'electronic systems'],
  AEF: ['Aerostat Foundation', 'construction parts'],
  AEN: ['Advanced STL Engine', 'ship engines'],
  AFP: ['Advanced Fuel Pump', 'ship engines'],
  AFR: ['Advanced Fuel Rod', 'ship engines'],
  AGS: ['Advanced High-G Seats', 'ship parts'],
  AHP: ['Advanced Hull Plate', 'ship parts'],
  AIR: ['Air Scrubber', 'construction parts'],
  AL: ['Aluminium', 'metals'],
  ALE: ['Stellar Pale Ale', 'consumables (luxury)'],
  ALG: ['Protein-Rich Algae', 'agricultural products'],
  ALO: ['Aluminium Ore', 'ores'],
  AMM: ['Ammonia', 'gases'],
  ANZ: ['Advanced Nozzle', 'ship engines'],
  APT: ['Advanced Thermal Protection Tile', 'ship shields'],
  AR: ['Argon', 'gases'],
  ARP: ['Advanced Anti-rad Plate', 'ship shields'],
  ASE: ['Advanced Structural Elements', 'construction prefabs'],
  AST: ['Alpha-Stabilized Titanium', 'alloys'],
  ATA: ['Advanced Transparent Aperture', 'construction prefabs'],
  ATP: ['Advanced Thermal Protection Material', 'ship parts'],
  AU: ['Gold', 'metals'],
  AUO: ['Gold Ore', 'ores'],
  AWF: ['Active Water Filter', 'electronic devices'],
  AWH: ['Advanced Whipple Shielding', 'ship shields'],
  BAC: ['Helpful Bacteria', 'chemicals'],
  BAI: ['Basic AI Framework', 'software components'],
  BBH: ['Basic Bulkhead', 'construction prefabs'],
  BCO: ['Budget Connectors', 'electronic pieces'],
  BDE: ['Basic Deck Elements', 'construction prefabs'],
  BE: ['Beryllium', 'elements'],
  BEA: ['Protein-Rich Beans', 'agricultural products'],
  BER: ['Beryl Crystals', 'minerals'],
  BFP: ['Basic Fuel Pump', 'ship engines'],
  BFR: ['Basic Fuel Rod', 'ship engines'],
  BGC: ['Shielded Connectors', 'electronic pieces'],
  BGO: ['Blue Gold', 'alloys'],
  BGS: ['Basic High-G Seats', 'ship parts'],
  BHP: ['Basic Hull Plate', 'ship parts'],
  BID: ['Full-Body Interaction Device', 'electronic devices'],
  BL: ['Breathable Liquid', 'chemicals'],
  BLE: ['Desaturation Agent', 'chemicals'],
  BMF: ['Basic Mainframe', 'electronic devices'],
  BND: ['Bandages', 'medical equipment'],
  BOR: ['Boron Crystals', 'minerals'],
  BOS: ['Borosilicate', 'alloys'],
  BPT: ['Basic Thermal Protection Tile', 'ship shields'],
  BR1: ['Command Bridge MK1', 'unit prefabs'],
  BR2: ['Command Bridge MK2', 'unit prefabs'],
  BRM: ['Bioreactive Minerals', 'minerals'],
  BRO: ['Bronze', 'alloys'],
  BRP: ['Basic Anti-rad Plate', 'ship shields'],
  BRS: ['Short-distance Command Bridge', 'unit prefabs'],
  BSC: ['Body Scanner', 'electronic devices'],
  BSE: ['Basic Structural Elements', 'construction prefabs'],
  BTA: ['Basic Transparent Aperture', 'construction prefabs'],
  BTS: ['Bacterial Tungsten Solution', 'liquids'],
  BWH: ['Basic Whipple Shielding', 'ship shields'],
  BWS: ['Basic Workstation', 'electronic devices'],
  C: ['Carbon', 'elements'],
  CA: ['Calcium', 'elements'],
  CAF: ['Caffeinated Beans', 'agricultural products'],
  CAP: ['Electric Field Capacitor', 'electronic pieces'],
  CBL: ['Large Capacitor Bank', 'energy systems'],
  CBM: ['Medium Capacitor Bank', 'energy systems'],
  CBS: ['Small Capacitor Bank', 'energy systems'],
  CC: ['Climate Controller', 'electronic systems'],
  CCD: ['Crowd Control Drone', 'drones'],
  CD: ['Capacitive Display', 'electronic parts'],
  CF: ['Ceramic Fabric', 'textiles'],
  CHA: ['Combustion Chamber', 'ship engines'],
  CL: ['Chlorine', 'elements'],
  CLI: ['Caliche Rock', 'minerals'],
  CMK: ['', 'construction materials'],
  COF: ['Caffeinated Infusion', 'consumables (luxury)'],
  COM: ['Communication System', 'electronic systems'],
  COT: ['Cotton Fabric', 'textiles'],
  CQL: ['Crew Quarters (Large)', 'unit prefabs'],
  CQM: ['Crew Quarters (Medium)', 'unit prefabs'],
  CQS: ['Crew Quarters (Small)', 'unit prefabs'],
  CQT: ['Crew Quarters (Tiny)', 'unit prefabs'],
  CRU: ['Cryogenic Unit', 'electronic systems'],
  CST: ['Cryogenic Stabilizer', 'chemicals'],
  CTF: ['Ceramic-Tungsten Fabric', 'textiles'],
  CU: ['Copper', 'metals'],
  CUO: ['Copper Ore', 'ores'],
  DA: ['Data Analyzer', 'software tools'],
  DCH: ['Drone Chassis', 'drones'],
  DCL: ['Durable Casing L', 'plastics'],
  DCM: ['Durable Casing M', 'plastics'],
  DCS: ['Durable Casing S', 'plastics'],
  DD: ['Distributed Database', 'software tools'],
  DDT: ['DDT Plant Agent', 'chemicals'],
  DEC: ['Decorative Elements', 'construction parts'],
  DIS: ['Information Display', 'electronic parts'],
  DOU: ['Drone Operations Unit', 'unit prefabs'],
  DRF: ['Drone Frame', 'drones'],
  DV: ['Data Visualizer', 'software tools'],
  DW: ['Drinking Water', 'consumables (basic)'],
  EDC: ['Entertainment Data Core', 'software tools'],
  EES: ['Enriched Einsteinium', 'chemicals'],
  ENG: ['Standard STL Engine', 'ship engines'],
  EPO: ['Epoxy Resin', 'construction materials'],
  ES: ['Einsteinium', 'elements'],
  ETC: ['Enriched Technetium', 'chemicals'],
  EXO: ['Exoskeleton Work Suit', 'consumables (basic)'],
  F: ['Fluorine', 'gases'],
  FAL: ['Ferrominium', 'alloys'],
  FAN: ['Active Cooling Device', 'electronic parts'],
  FC: ['Flow Control Device', 'construction parts'],
  FE: ['Iron', 'metals'],
  FEO: ['Iron Ore', 'ores'],
  FET: ['Ferro-Titanium', 'alloys'],
  FF: ['FTL Fuel', 'fuels'],
  FFC: ['FTL Field Controller', 'electronic systems'],
  FIM: ['Flavoured Insta-Meal', 'consumables (basic)'],
  FIR: ['Fission Reactor', 'ship engines'],
  FLO: ['Floating Tank', 'construction parts'],
  FLP: ['Fluid Piping', 'construction parts'],
  FLX: ['Flux', 'chemicals'],
  FOD: ['All-Purpose Fodder', 'agricultural products'],
  FSE: ['Fuel-saving STL Engine', 'ship engines'],
  FUN: ['Entertainment Unit', 'unit prefabs'],
  GAL: ['Galerite Rock', 'minerals'],
  GC: ['Cylindrical Gas Container', 'construction parts'],
  GCH: ['Glass Combustion Chamber', 'ship engines'],
  GEN: ['Glass-based STL Engine', 'ship engines'],
  GIN: ['Einsteinium-Infused Gin', 'consumables (luxury)'],
  GL: ['Glass', 'construction materials'],
  GNZ: ['Glass Nozzle', 'ship engines'],
  GRA: ['Wine-Quality Grapes', 'agricultural products'],
  GRN: ['High-Carb Grains', 'agricultural products'],
  GV: ['Gas Vent', 'construction parts'],
  H: ['Hydrogen', 'gases'],
  H2O: ['Water', 'liquids'],
  HAB: ['Habitat Unit', 'unit prefabs'],
  HAL: ['Halite Crystals', 'minerals'],
  HCC: ['High-Capacity Connectors', 'electronic pieces'],
  HCP: ['Hydrocarbon Plants', 'agricultural products'],
  HD: ['Holographic Display', 'electronic devices'],
  HE: ['Helium', 'gases'],
  HE3: ['Helium-3 Isotope', 'gases'],
  HER: ['Spicy Herbs', 'agricultural products'],
  HEX: ['Heliotrope Extract', 'liquids'],
  HHP: ['Hardened Hull Plate', 'ship parts'],
  HMS: ['HazMat Work Suit', 'consumables (basic)'],
  HNZ: ['Hyperthrust Nozzle', 'ship engines'],
  HOG: ['Holographic Glasses', 'electronic devices'],
  HOP: ['Flowery Hops', 'agricultural products'],
  HPC: ['Handheld Personal Console', 'electronic devices'],
  HPR: ['High-power FTL Reactor', 'ship engines'],
  HSE: ['Hardened Structural Elements', 'construction prefabs'],
  HSS: ['Smart Space Suit', 'consumables (basic)'],
  HTE: ['Hyperthrust STL Engine', 'ship engines'],
  HYR: ['Hyper-power Reactor', 'ship engines'],
  I: ['Iodine', 'elements'],
  IDC: ['Information Data Core', 'software systems'],
  IMM: ['Information Management System', 'software systems'],
  IND: ['Indigo Colorant', 'chemicals'],
  INS: ['InsuFoam', 'construction materials'],
  JUI: ['Sedative Substance', 'chemicals'],
  KOM: ['Kombucha', 'consumables (luxury)'],
  KV: ['Kevlar Fabric', 'textiles'],
  LBH: ['Lightweight Bulkhead', 'construction prefabs'],
  LC: ['AI-Assisted Lab Coat', 'consumables (basic)'],
  LCB: ['Large Cargo Bay Kit', 'ship kits'],
  LCR: ['Liquid Crystals', 'chemicals'],
  LD: ['Local Database', 'software components'],
  LDE: ['Lightweight Deck Elements', 'construction prefabs'],
  LDI: ['Laser Diodes', 'electronic pieces'],
  LES: ['Liquid Einsteinium', 'liquids'],
  LFE: ['Large FTL Emitter', 'ship engines'],
  LFL: ['Large FTL Fuel Tank Kit', 'ship kits'],
  LFP: ['Low-heat Fuel Pump', 'ship engines'],
  LHP: ['Lightweight Hull Plate', 'ship parts'],
  LI: ['Lithium', 'metals'],
  LIO: ['Lithium Ore', 'ores'],
  LIS: ['Life Support System', 'electronic systems'],
  LIT: ['Neon Lighting System', 'construction parts'],
  LOG: ['Logistics System', 'electronic systems'],
  LSE: ['Lightweight Structural Elements', 'construction prefabs'],
  LSL: ['Large STL Fuel Tank Kit', 'ship kits'],
  LST: ['Limestone', 'minerals'],
  LTA: ['Lightweight Transparent Aperture', 'construction prefabs'],
  LU: ['Laboratory Unit', 'unit prefabs'],
  MAG: ['Magnetite', 'minerals'],
  MAI: ['High-Carb Maize', 'agricultural products'],
  MB: ['Motherboard', 'electronic parts'],
  MCB: ['Medium Cargo Bay Kit', 'ship kits'],
  MCG: ['Mineral Construction Granulate', 'construction materials'],
  MEA: ['Quality Meat Meal', 'consumables (basic)'],
  MED: ['Basic Medical Kit', 'consumables (basic)'],
  MFE: ['Medium FTL Emitter', 'ship engines'],
  MFK: ['Medium Fastener Kit', 'electronic pieces'],
  MFL: ['Medium FTL Fuel Tank Kit', 'ship kits'],
  MG: ['Magnesium', 'elements'],
  MGC: ['Magnetic Ground Cover', 'construction parts'],
  MGS: ['Magnesite', 'minerals'],
  MHL: ['Metal-Halide Lighting System', 'construction parts'],
  MHP: ['Micro Headphones', 'electronic devices'],
  MLI: ['Machine Learning Interface', 'software components'],
  MPC: ['Micro-Processor', 'electronic parts'],
  MSL: ['Medium STL Fuel Tank Kit', 'ship kits'],
  MTC: ['MegaTube Coating', 'construction materials'],
  MTP: ['Meat Tissue Patties', 'agricultural products'],
  MUS: ['Protein-Rich Mushrooms', 'agricultural products'],
  MWF: ['Medium Wafer', 'electronic pieces'],
  N: ['Nitrogen', 'gases'],
  NA: ['Sodium', 'elements'],
  NAB: ['Sodium Borohydride', 'chemicals'],
  NCS: ['Nano-Carbon Sheeting', 'construction materials'],
  NE: ['Neon', 'gases'],
  NF: ['Networking Framework', 'software components'],
  NFI: ['Nano Fiber', 'construction materials'],
  NG: ['Nano-Coated Glass', 'construction materials'],
  NL: ['Nylon Fabric', 'textiles'],
  NN: ['Neural Network', 'software tools'],
  NOZ: ['Basic Nozzle', 'ship engines'],
  NR: ['Nano-Enhanced Resin', 'chemicals'],
  NS: ['Nutrient Solution', 'chemicals'],
  NST: ['NeuroStimulants', 'consumables (luxury)'],
  NUT: ['Triglyceride Nuts', 'agricultural products'],
  NV1: ['Navigation Module MK1', 'ship parts'],
  NV2: ['Navigation Module MK2', 'ship parts'],
  O: ['Oxygen', 'gases'],
  OFF: ['Office Supplies', 'utility'],
  OLF: ['Olfactory Substances', 'chemicals'],
  OS: ['Operating System', 'software tools'],
  OVE: ['Basic Overalls', 'consumables (basic)'],
  PCB: ['Printed Circuit Board', 'electronic parts'],
  PDA: ['Personal Data Assistant', 'consumables (basic)'],
  PE: ['Poly-Ethylene', 'plastics'],
  PFE: ['Premium Fertilizer', 'chemicals'],
  PG: ['Polymer Granulate', 'plastics'],
  PIB: ['Pineberries', 'agricultural products'],
  PK: ['Painkillers', 'medical equipment'],
  POW: ['Power Cell', 'energy systems'],
  PPA: ['Protein Paste', 'agricultural products'],
  PSH: ['Pressure Shielding', 'construction parts'],
  PSL: ['Polymer Sheet Type L', 'plastics'],
  PSM: ['Polymer Sheet Type M', 'plastics'],
  PSS: ['Polymer Sheet Type S', 'plastics'],
  PT: ['Power Tools', 'consumables (basic)'],
  PWO: ['Padded Work Overall', 'consumables (luxury)'],
  QCR: ['Quick-charge FTL Reactor', 'ship engines'],
  RAD: ['Radio Device', 'electronic devices'],
  RAG: ['Radioisotope Generator', 'ship engines'],
  RAM: ['Memory Bank', 'electronic parts'],
  RAT: ['Basic Rations', 'consumables (basic)'],
  RBH: ['Reinforced Bulkhead', 'construction prefabs'],
  RCO: ['Raw Cotton Fiber', 'agricultural products'],
  RCS: ['Reactor Control System', 'ship engines'],
  RCT: ['Standard FTL Reactor', 'ship engines'],
  RDE: ['Reinforced Deck Elements', 'construction prefabs'],
  RDL: ['Large Ship-Repair Drone Operations Unit', 'unit prefabs'],
  RDS: ['Small Ship-Repair Drone Operations Unit', 'unit prefabs'],
  REA: ['Chemical Reagents', 'chemicals'],
  RED: ['Rescue Drone', 'drones'],
  REP: ['Repair Kit', 'consumables (luxury)'],
  RG: ['Reinforced Glass', 'construction materials'],
  RGO: ['Red Gold', 'alloys'],
  RHP: ['Reinforced Hull Plate', 'ship parts'],
  ROM: ['Non-Volatile Memory', 'electronic parts'],
  RSE: ['Reinforced Structural Elements', 'construction prefabs'],
  RSH: ['Radiation Shielding', 'construction parts'],
  RSI: ['Raw Silk Strains', 'agricultural products'],
  RTA: ['Reinforced Transparent Aperture', 'construction prefabs'],
  S: ['Sulfur', 'elements'],
  SA: ['Search Algorithm', 'software components'],
  SAL: ['Sorting Algorithm', 'software components'],
  SAR: ['Sensor Array', 'electronic devices'],
  SC: ['Stem Cell Treatment', 'consumables (luxury)'],
  SCB: ['Small Cargo Bay Kit', 'ship kits'],
  SCN: ['Multi-Purpose Scanner', 'consumables (basic)'],
  SCR: ['Sulfur Crystals', 'minerals'],
  SDR: ['Surgical Drone', 'drones'],
  SEA: ['Poly-Sulfite Sealant', 'construction materials'],
  SEN: ['Sensor', 'electronic parts'],
  SEQ: ['Surgical Equipment', 'medical equipment'],
  SF: ['STL Fuel', 'fuels'],
  SFE: ['Small FTL Emitter', 'ship engines'],
  SFK: ['Small Fastener Kit', 'electronic pieces'],
  SFL: ['Small FTL Fuel Tank Kit', 'ship kits'],
  SI: ['Silicon', 'metals'],
  SIL: ['Silken Fabric', 'textiles'],
  SIO: ['Silicon Ore', 'ores'],
  SNM: ['Spatial Navigation Map', 'software systems'],
  SOI: ['Artificial Soil', 'chemicals'],
  SOL: ['Solar Cell', 'energy systems'],
  SP: ['Solar Panel', 'energy systems'],
  SRD: ['Ship-Repair Drone', 'drones'],
  SRP: ['Specialized Anti-rad Plate', 'ship shields'],
  SSC: ['Structural Spacecraft Component', 'ship parts'],
  SSL: ['Small STL Fuel Tank Kit', 'ship kits'],
  STL: ['Steel', 'metals'],
  STR: ['Medical Stretcher', 'medical equipment'],
  STS: ['Stability Support System', 'electronic systems'],
  SU: ['Surgery Unit', 'unit prefabs'],
  SUD: ['Surveillance Drone', 'drones'],
  SUN: ['Safety Uniform', 'utility'],
  SWF: ['Small Wafer', 'electronic pieces'],
  TA: ['Tantalum', 'elements'],
  TAC: ['Targeting Computer', 'electronic systems'],
  TAI: ['Tantalite Rock', 'minerals'],
  TC: ['Technetium', 'elements'],
  TCB: ['Tiny Cargo Bay Kit', 'ship kits'],
  TCL: ['TCL Acid', 'chemicals'],
  TCO: ['Technetium Oxide', 'minerals'],
  TCS: ['Stabilized Technetium', 'construction parts'],
  TCU: ['Trauma Care Unit', 'unit prefabs'],
  THF: ['ThermoFluid', 'chemicals'],
  THP: ['Basic Thermal Protection Material', 'ship parts'],
  TI: ['Titanium', 'metals'],
  TIO: ['Titanium Ore', 'ores'],
  TK: ['TechnoKevlar Fabric', 'textiles'],
  TPU: ['Tensor Processing Unit', 'electronic parts'],
  TRA: ['Audio Transmitter', 'electronic parts'],
  TRN: ['Advanced Transistor', 'electronic pieces'],
  TRU: ['Truss', 'construction parts'],
  TS: ['Tectosilisite', 'minerals'],
  TSH: ['Thermal Shielding', 'construction parts'],
  TUB: ['Test Tubes', 'medical equipment'],
  UTS: ['Universal Toolset', 'utility'],
  VCB: ['High-volume Cargo Bay Kit', 'ship kits'],
  VEG: ['Triglyceride Fruits', 'agricultural products'],
  VG: ['VitaGel', 'consumables (luxury)'],
  VIT: ['Vita Essence', 'agricultural products'],
  VSC: ['Very Small Cargo Bay Kit', 'ship kits'],
  W: ['Tungsten', 'metals'],
  WAI: ['Weak Artificial Intelligence', 'software systems'],
  WAL: ['Alpha-Stabilized Tungsten', 'alloys'],
  WCB: ['High-load Cargo Bay Kit', 'ship kits'],
  WIN: ['Smart Zinfandel', 'consumables (luxury)'],
  WM: ['Window Manager', 'software components'],
  WOR: ['Handcraft Workshop Unit', 'unit prefabs'],
  WR: ['Water Reclaimer', 'electronic systems'],
  WS: ['Scientific Work Station', 'consumables (basic)'],
  ZIR: ['Zircon Crystals', 'minerals'],
  ZR: ['Zirconium', 'elements'],
};

export const MaterialNameToTicker = {};
for (const ticker in MaterialNames) {
  MaterialNameToTicker[MaterialNames[ticker][0]] = ticker;
}
