/**
 * A list of the material names and their corresponding ticker, weight, and volume. Makes it easier to reference FIO data
 *
 */

export const CurrencySymbols = {
  CIS: '₡',
  AIC: '₳',
  NCC: '₦',
  ICA: 'ǂ',
  ECD: '€',
};
export const FactionHeaders = {
  'Castillo-Ito': 'CI',
  Insitor: 'IC',
  Antares: 'AI',
  'NEO Charter': 'NC',
};
export const RatingColors = {
  P: '#1b6b9c',
  U: '#8b211e',
  F: '#e26c37',
  E: '#e7782b',
  D: '#e87d28',
  C: '#ed891c',
  B: '#f19510',
  A: '#f6a204',
};

export const Consumption = {
  PIO: {
    RAT: 4,
    DW: 4,
    OVE: 0.5,
    PWO: 0.2,
    COF: 0.5,
  },
  SET: {
    DW: 5,
    RAT: 6,
    EXO: 0.5,
    PT: 0.5,
    KOM: 1,
    REP: 0.2,
  },
  TEC: {
    DW: 7.5,
    RAT: 7,
    MED: 0.5,
    HMS: 0.5,
    SCN: 0.1,
    ALE: 1,
    SC: 0.1,
  },
  ENG: {
    DW: 10,
    MED: 0.5,
    FIM: 7,
    HSS: 0.2,
    PDA: 0.1,
    VG: 0.2,
    GIN: 1,
  },
  SCI: {
    DW: 10,
    MED: 0.5,
    MEA: 7,
    LC: 0.2,
    WS: 0.1,
    WIN: 1,
    NST: 0.1,
  },
};

export const Exchanges = {
  'Antares Station Commodity Exchange': 'ANT',
  'Benten Station Commodity Exchange': 'BEN',
  'Moria Station Commodity Exchange': 'MOR',
  'Hortus Station Commodity Exchange': 'HRT',
  'Hubur Commodity Exchange': 'HUB',
  'Arclight Commodity Exchange': 'ARC',
};
export const ExchangeTickers = { ANT: 'AI1', BEN: 'CI1', MOR: 'NC1', HRT: 'IC1', HUB: 'NC2', ARC: 'CI2' };
export const ExchangeTickersReverse = {
  AI1: 'ANT',
  CI1: 'BEN',
  NC1: 'MOR',
  IC1: 'HRT',
  NC2: 'HUB',
  CI2: 'ARC',
};
export const Stations = {
  'Antares Station': 'ANT',
  'Benten Station': 'BEN',
  'Moria Station': 'MOR',
  'Hortus Station': 'HRT',
  'Hubur Station': 'HUB',
  'Arclight Station': 'ARC',
};

export const NonProductionBuildings = ['CM', 'HB1', 'HB2', 'HB3', 'HB4', 'HB5', 'HBB', 'HBC', 'HBL', 'HBM', 'STO'];

export const FriendlyNames = {
  LocalMarketAds: 'LM Unit Prices',
  OrderETAs: 'Order ETAs',
  FlightETAs: 'Flight Planning ETAs',
  ShippingAds: 'LM Shipping Rates',
  PostLM: 'LM Posting Unit Price',
  ContractDrafts: 'CONTD Unit Prices',
  QueueLoad: 'Queue Percent Display',
  ConsumableTimers: 'Workforce Consumable Burn',
  FleetETAs: 'Fleet ETAs',
  Notifications: 'Notifications',
  ScreenUnpack: 'Screen Unpack',
  ImageCreator: 'Chat Image Creator',
  InventoryOrganizer: 'Inventory Sorting',
  CommandCorrecter: 'Command Correcter',
  CalculatorButton: 'Calculator Button',
  Sidebar: 'Sidebar',
  HeaderMinimizer: 'Minimize Headers (Master)',
  PendingContracts: 'Pending Contracts',
  CompactUI: 'Compact UI',
  FormulaReplacer: 'Formula Replacer',
  AdvancedMode: 'Advanced Minimialist Mode (Master)',
  CXOBHighlighter: 'CXOB Name Highlighter',
  CXPOOrderBook: 'CXPO Order Book',
  ChatDeleteButton: 'Toggle Chat Delete (Master)',
};

export const SortingTriangleHTML = `
<div title=""><svg aria-hidden="true" width="10" height="10" role="img" version="1.1" fill="currentcolor" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24" style="vertical-align: middle;"><g><path d="M.88681 1.097752l12.13774 21.02318L25.422964 1.105446z"></path></g></svg></div>`;

export const PlanetCommands = [
  'ADM',
  'BSC',
  'COGC',
  'COGCPEX',
  'COGCU',
  'FLTP',
  'LR',
  'LMP',
  'LM',
  'PLI',
  'POPI',
  'POPR',
  'PPS',
  'SHY',
  'WAR',
  'BS',
  'BRA',
  'GOV',
];

export const SystemNames = {
  ARCLIGHT: 'AM-783',
  'FORGE-KEEP': 'FK-371',
  'WET WATER': 'FK-794',
  'CAYMAN PLANETS': 'GC-645',
  'MOUNT OLYMPUS': 'HM-049',
  GATEWAY: 'HM-223',
  'NEO EDEN': 'JS-299',
  EBISU: 'JS-952',
  BASTABLON: 'KW-020',
  DOLZENA: 'LG-418',
  'ANTARES V': 'LS-300',
  TRINITY: 'OF-259',
  GUNDABAD: 'OT-442',
  MORIA: 'OT-580',
  'OUTER HEAVEN': 'PG-899',
  AURUM: 'QJ-650',
  ACETARES: 'QJ-684',
  HUBUR: 'TD-203',
  HOTEI: 'UV-135',
  BENTEN: 'UV-351',
  DAIKOKU: 'UV-796',
  RATHAR: 'VH-043',
  HORTUS: 'VH-331',
  MIDWAY: 'WB-675',
  BASTION: 'XG-326',
  'ANTARES III': 'ZV-194',
  'ANTARES I': 'ZV-307',
  'ANTARES II': 'ZV-759',
  'ANTARES IV': 'ZV-896',
};

export const PlanetNames = {
  LEMURIA: 'AJ-768a',
  GALLUS: 'AM-783b',
  EMENTIOR: 'AM-783c',
  TYPHON: 'AU-522b',
  'NOVA HONSHU': 'BS-788c',
  TACOTOPIA: 'CB-045b',
  JOTU: 'CG-044c',
  PYRGOS: 'CH-771a',
  TALOSIA: 'DC-823b',
  ORM: 'DW-456g',
  MANIFOLD: 'EL-179b',
  'NOVA UNALASKA': 'EZ-476b',
  TOKTU: 'FK-037f',
  'LA FORGE': 'FK-371b',
  BOUCHER: 'FK-794b',
  EPICIER: 'FK-794c',
  VAULT: 'GC-645b',
  CHU: 'GY-110c',
  POSEIDON: 'HM-049b',
  APOTHECARY: 'IA-603b',
  ELECTRONICA: 'IY-028c',
  NEMESIS: 'JS-299a',
  GIBSON: 'JS-952c',
  AUSTRALIA: 'KI-446a',
  DEMETER: 'KI-446b',
  HERMES: 'KI-448b',
  ROCK: 'KQ-966b',
  MILLIWAYS: 'KW-020c',
  'GIEDI PRIME': 'KW-358b',
  ETHERWIND: 'KW-688c',
  KINZA: 'LG-418b',
  'PLANET MC PLANETFACE': 'LG-913e',
  ARATORA: 'LS-231b',
  GRIFFONSTONE: 'LS-300c',
  JURA: 'OF-259d',
  BERTHIER: 'OF-375b',
  ADALINA: 'OF-375c',
  AKKALA: 'OF-586b',
  DANAKIL: 'OT-442b',
  MANAKIL: 'OT-442h',
  IIRON: 'OT-580a',
  MONTEM: 'OT-580b',
  VALLIS: 'OT-580c',
  PALLADA: 'OT-580d',
  PRISM: 'OT-889a',
  JEETIYU: 'OT-889b',
  ASHLAND: 'PD-754d',
  SALADIN: 'PG-899b',
  NASCENT: 'QJ-149c',
  ELON: 'QJ-650c',
  'LOM PALANKA': 'QJ-684a',
  ACELAND: 'QJ-684b',
  CIRCA: 'QQ-001a',
  CIRCE: 'QQ-001b',
  CELEBDIL: 'QQ-645b',
  MALAHAT: 'RC-040b',
  IRONFORGE: 'RC-040c',
  'ICE STATION ALPHA': 'SE-110c',
  SHEOL: 'TD-203b',
  RHAZES: 'TD-228b',
  SABATON: 'TO-392d',
  ALYAZKCALB: 'UB-402e',
  'ASBESTOS LEAD ASBESTOS': 'UV-072c',
  KATOA: 'UV-351a',
  YANNICK: 'UV-351b',
  UMBRA: 'UV-351c',
  BIOGENESIS: 'UV-351d',
  PROXION: 'UV-796b',
  PHANTASM: 'VH-043a',
  NOBELION: 'VH-043c',
  PROMITOR: 'VH-331a',
  'HELION PRIME': 'VH-331d',
  SHIPTRONIA: 'VH-331e',
  ODYSSEUS: 'VH-331f',
  AVALON: 'VH-331g',
  HYDRON: 'VH-331i',
  SHESMU: 'VH-778b',
  SAND: 'WB-675c',
  GASWORLD: 'WB-675i',
  MIMAR: 'WC-702b',
  MAGUS: 'XD-354b',
  TITAN: 'XG-326b',
  FROST: 'XG-326d',
  UPONOR: 'XH-329a',
  LIBERTAS: 'XH-594a',
  KIRUNA: 'XH-594b',
  CORTEZ: 'XH-594c',
  KUB: 'YI-059f',
  HARPINA: 'YI-209h',
  ARCADIA: 'YI-683c',
  VERDANT: 'YI-715b',
  NORWICK: 'YK-649b',
  NIKE: 'ZV-194a',
  HEPHAESTUS: 'ZV-307c',
  PHOBOS: 'ZV-307d',
  ASTRAEUS: 'ZV-307e',
  VULCAN: 'ZV-759b',
  DEIMOS: 'ZV-759c',
  HARMONIA: 'ZV-896b',
  LIFE: 'ZV-896c',
};
