<script setup lang="ts">
import { useXitParameters } from '@src/hooks/use-xit-parameters';
import SectionHeader from '@src/components/SectionHeader.vue';
import PrunLink from '@src/components/PrunLink.vue';

const parameters = useXitParameters();

const isAction = ['ACT', 'ACTION', 'ACTIONS'].includes(parameters[0]?.toUpperCase());
</script>

<template>
  <template v-if="isAction">
    <SectionHeader>What are action packages?</SectionHeader>
    <div style="margin: 5px">
      An action package is a series of preprogrammed actions that can be nearly automated with the
      click of a few buttons. Action packages exist in two main forms: The groups and actions you
      input to generate them, and the list of actions compiled by PMMG to execute them. First, a set
      of material groups are defined (resupply a base, repair a building, etc.). Second, a group of
      actions are defined using those material groups (buy the resupply supplies from the CX, etc.).
      These two steps are taken on the generation screen. Lastly, on the execution screen the groups
      and actions are parsed into a series of individual actions on the PrUn interface (buy 100 COF
      @ 400, etc.).
    </div>
    <SectionHeader>How do I make an action package?</SectionHeader>
    <div style="margin: 5px">
      Open the XIT ACTION buffer and click "CREATE NEW" or enter XIT_ACTION_EDIT_{name} into a new
      buffer. Begin by adding the material groups you will be working with. Next, add the actions
      corresponding to those material groups. Click "SAVE" to save to local storage. The "EXECUTE"
      button opens the execution screen.
    </div>
    <SectionHeader>How do I execute an action package?</SectionHeader>
    <div style="margin: 5px">
      After creating the action package, its execution screen is accessed through the XIT ACTION
      buffer or through XIT ACTION_{name} directly. The "VIEW" button displays the individual
      actions parsed from the actions and groups previously assigned. The "VALIDATE" button checks
      to make sure all buffers are present and the execution will run smoothly. Note that the
      "EXECUTE" action automatically runs validation before starting. The "EXECUTE" button begins
      the execution of the action package. Relevant buttons are moved onto the buffer and the user
      only has to click through them. Any error messages will appear in the message box if they
      arise.
    </div>
    <SectionHeader>What do I need to execute an action package?</SectionHeader>
    <div style="margin: 5px">
      You must have all the relevant buffers or tiles (CXPO for example) present on the screen
      before the action package will begin executing. The CXP data generated by opening a CXPO
      buffer must also have been successfully recorded by PMMG.
    </div>
  </template>
  <template v-else>
    <table>
      <thead>
        <tr>
          <th>I want to...</th>
          <th>Command</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Change Refined PrUn settings.</td>
          <td>
            <PrunLink command="XIT SET" />
          </td>
        </tr>
        <tr>
          <td>Change the feature set to Basic/Full.</td>
          <td>
            <PrunLink command="XIT SET FEAT" />
          </td>
        </tr>
        <tr>
          <td>Disable some Refined PrUn feature.</td>
          <td>
            <PrunLink command="XIT SET FEAT" />
          </td>
        </tr>
        <tr>
          <td>Find out which XIT commands are available.</td>
          <td>
            <PrunLink command="XIT CMDS" />
          </td>
        </tr>
        <tr>
          <td>Import PMMG settings.</td>
          <td>
            <PrunLink command="XIT SET PMMG" />
          </td>
        </tr>
        <tr>
          <td>Get a random corgi gif.</td>
          <td>
            <PrunLink command="XIT GIF CORGI" />
          </td>
        </tr>
      </tbody>
    </table>
  </template>
</template>

<style module></style>
